/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiAssistant: typeof import('./components/ai/AiAssistant.vue')['default']
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    BigOptionButton: typeof import('./components/common/BigOptionButton.vue')['default']
    BottomTab: typeof import('./components/layout/BottomTab.vue')['default']
    DemoBadge: typeof import('./components/common/DemoBadge.vue')['default']
    DemoCard: typeof import('./components/common/DemoCard.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    GlobalSpeechToggle: typeof import('./components/common/GlobalSpeechToggle.vue')['default']
    MetricCard: typeof import('./components/common/MetricCard.vue')['default']
    MoodIcon: typeof import('./components/common/MoodIcon.vue')['default']
    RecipeCard: typeof import('./components/common/RecipeCard.vue')['default']
    RouteErrorBoundary: typeof import('./components/common/RouteErrorBoundary.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuleCard: typeof import('./components/common/RuleCard.vue')['default']
    ScoreRing: typeof import('./components/common/ScoreRing.vue')['default']
    SideNav: typeof import('./components/layout/SideNav.vue')['default']
    SubstitutionChip: typeof import('./components/common/SubstitutionChip.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
